# Generated by Django 4.2.16 on 2024-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='status',
            field=models.CharField(default='unsent', max_length=10),
        ),
    ]
