# Generated by Django 4.2.16 on 2024-12-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0004_emailtemplate_emailschedule_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Unique name for the template', max_length=255, unique=True),
        ),
    ]
