# Generated by Django 4.2.16 on 2024-12-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0005_alter_emailtemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Select a template for this email schedule (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_scheduler.emailtemplate'),
        ),
    ]
