# Generated by Django 4.2.16 on 2024-12-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0007_emailschedule_created_at_emailschedule_updated_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailschedule',
            index=models.Index(fields=['send_date'], name='email_sched_send_da_1d211e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailschedule',
            index=models.Index(fields=['status'], name='email_sched_status_6475c4_idx'),
        ),
    ]
