# Generated by Django 4.2.16 on 2024-12-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0008_emailschedule_email_sched_send_da_1d211e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailschedule',
            name='email_sched_send_da_1d211e_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailschedule',
            name='email_sched_status_6475c4_idx',
        ),
    ]
