# Generated by Django 4.2.16 on 2025-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scheduler', '0009_remove_emailschedule_email_sched_send_da_1d211e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailschedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='emailschedule',
            index=models.Index(fields=['send_date'], name='email_sched_send_da_1d211e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailschedule',
            index=models.Index(fields=['status'], name='email_sched_status_6475c4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailschedule',
            index=models.Index(fields=['created_at'], name='email_sched_created_d8ceb4_idx'),
        ),
    ]
